---
- name: Update package list on Debian-based systems
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
- name: Upgrade all packages on Debian-based systems
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian"
- name: Update package list on Red Hat-based systems
  yum:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
- name: Upgrade all packages on Red Hat-based systems
  yum:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
